#!/bin/bash
# 🧪 Reports Page - Visual Testing Checklist
# Run this after loading reports.php in browser

echo "========================================"
echo "📊 REPORTS PAGE - TESTING CHECKLIST"
echo "========================================"
echo ""
echo "📝 Instructions:"
echo "1. Open reports.php in browser"
echo "2. Open browser console (F12)"
echo "3. Check each item below"
echo ""
echo "========================================"
echo "✅ BROWSER CONSOLE CHECKS"
echo "========================================"
echo ""
echo "□ No JavaScript errors?"
echo "□ No 'Chart is not defined' errors?"
echo "□ No 'Canvas already in use' errors?"
echo "□ See 'Advanced Reports initializing...' message?"
echo "□ See '✅ Reports 2.0 loaded' message?"
echo ""
echo "========================================"
echo "✅ VISUAL ELEMENT CHECKS"
echo "========================================"
echo ""
echo "□ Page loads without errors (no white screen)?"
echo "□ Four KPI cards at top visible?"
echo "  - Total Revenue"
echo "  - Units Sold"
echo "  - Average Order Value"
echo "  - Fulfillment Rate"
echo ""
echo "□ 30/60/90 Day Metrics table visible?"
echo "  - Has 3 rows (30, 60, 90 days)"
echo "  - Shows Orders, Units Sold, Revenue columns"
echo "  - Has icons and color coding"
echo ""
echo "□ Revenue Trend Chart renders?"
echo "  - Line chart showing monthly trend"
echo "  - Green line visible"
echo "  - Axes labeled correctly"
echo "  - No error messages"
echo ""
echo "□ Status Breakdown Chart renders?"
echo "  - Doughnut chart visible"
echo "  - Multiple colored segments"
echo "  - Legend at bottom"
echo "  - No error messages"
echo ""
echo "□ Product Performance table visible?"
echo "  - Shows top products"
echo "  - Has product names and revenue"
echo ""
echo "========================================"
echo "✅ INTERACTION CHECKS"
echo "========================================"
echo ""
echo "□ Week navigation buttons work?"
echo "  - Previous Week button"
echo "  - Next Week button"
echo "  - Charts update without errors?"
echo ""
echo "□ ML Forecast section available?"
echo "  - Clickable link/button"
echo "  - Opens forecast view"
echo "  - Forecast chart renders"
echo ""
echo "□ Date filter works?"
echo "  - Can select custom date range"
echo "  - Data updates correctly"
echo "  - Charts refresh without errors"
echo ""
echo "========================================"
echo "✅ CHART REFRESH TEST (IMPORTANT)"
echo "========================================"
echo ""
echo "This tests the canvas reuse fix:"
echo ""
echo "1. Load reports.php fresh"
echo "2. Wait for charts to render"
echo "3. Click 'Previous Week' or change date filter"
echo "4. Check console for errors"
echo ""
echo "□ Charts update without errors?"
echo "□ No 'Canvas already in use' error?"
echo "□ Both charts re-render successfully?"
echo ""
echo "========================================"
echo "✅ MOBILE RESPONSIVE CHECK (Optional)"
echo "========================================"
echo ""
echo "□ Resize browser to mobile width (< 768px)"
echo "□ All elements stack vertically?"
echo "□ Charts remain readable?"
echo "□ 30/60/90 table fits screen?"
echo ""
echo "========================================"
echo "🎯 EXPECTED RESULTS"
echo "========================================"
echo ""
echo "✅ All charts render without errors"
echo "✅ 30/60/90 metrics table visible and populated"
echo "✅ Zero console errors"
echo "✅ Charts update smoothly when filters applied"
echo "✅ Page is responsive on mobile"
echo ""
echo "========================================"
echo "🐛 IF YOU SEE ERRORS"
echo "========================================"
echo ""
echo "1. Screenshot the console error"
echo "2. Note which chart is failing"
echo "3. Check if Chart.js CDN loaded:"
echo "   - In console type: typeof Chart"
echo "   - Should return 'function' not 'undefined'"
echo ""
echo "4. Check if canvas elements exist:"
echo "   - In console type: document.getElementById('revenueTrendChart')"
echo "   - Should return <canvas> element not null"
echo ""
echo "========================================"
echo "📋 QUICK FIX REFERENCE"
echo "========================================"
echo ""
echo "Error: 'Chart is not defined'"
echo "Fix: Check reports.php has Chart.js CDN (line ~177)"
echo ""
echo "Error: 'Canvas already in use'"
echo "Fix: Check 15-reports.js has Chart.getChart() + destroy() logic"
echo ""
echo "Error: Charts not rendering"
echo "Fix: Check browser console for specific error message"
echo ""
echo "========================================"
echo "✅ TESTING COMPLETE"
echo "========================================"
echo ""
echo "If all checks pass:"
echo "🎉 Reports page is production ready!"
echo ""
echo "If any checks fail:"
echo "📧 Report the failing check and console errors"
echo ""
echo "========================================"
